import 'dart:async';

import 'package:drift/drift.dart';
import 'package:drift/wasm.dart';

import 'foreign_keys.dart';

// Shared with lib/core/backup/backup_web.dart, which needs the same name to
// probe for, export and restore the database.
const databaseName = 'duka_pos';

// sqlite3.wasm and drift_worker.js in web/ must be the prebuilt assets
// matching the pinned `sqlite3` and `drift` package versions in pubspec.yaml
// (downloaded from their GitHub releases, not generated by build_runner).
final sqlite3Uri = Uri.parse('sqlite3.wasm');
final driftWorkerUri = Uri.parse('drift_worker.js');

/// The one place that knows how to open this app's wasm database.
///
/// [initializeDatabase] is only consulted when no stored database exists —
/// which is exactly the hook the restore flow in `core/backup/backup_web.dart`
/// uses to seed a fresh database from an uploaded backup file.
Future<WasmDatabaseResult> openWasmDatabase({
  FutureOr<Uint8List?> Function()? initializeDatabase,
}) {
  return WasmDatabase.open(
    databaseName: databaseName,
    sqlite3Uri: sqlite3Uri,
    driftWorkerUri: driftWorkerUri,
    localSetup: enableForeignKeys,
    initializeDatabase: initializeDatabase,
  );
}

QueryExecutor openConnection() {
  return DatabaseConnection.delayed(
    Future(() async {
      final result = await openWasmDatabase();

      if (result.missingFeatures.isNotEmpty) {
        // ignore: avoid_print
        print(
          'duka_pos: using ${result.chosenImplementation} due to missing '
          'browser features: ${result.missingFeatures}',
        );
      }

      return result.resolvedExecutor;
    }),
  );
}
