import 'package:drift/drift.dart';
import 'package:drift/wasm.dart';

import 'foreign_keys.dart';

// sqlite3.wasm and drift_worker.js in web/ must be the prebuilt assets
// matching the pinned `sqlite3` and `drift` package versions in pubspec.yaml
// (downloaded from their GitHub releases, not generated by build_runner).
QueryExecutor openConnection() {
  return DatabaseConnection.delayed(
    Future(() async {
      final result = await WasmDatabase.open(
        databaseName: 'duka_pos',
        sqlite3Uri: Uri.parse('sqlite3.wasm'),
        driftWorkerUri: Uri.parse('drift_worker.js'),
        localSetup: enableForeignKeys,
      );

      if (result.missingFeatures.isNotEmpty) {
        // ignore: avoid_print
        print(
          'duka_pos: using ${result.chosenImplementation} due to missing '
          'browser features: ${result.missingFeatures}',
        );
      }

      return result.resolvedExecutor;
    }),
  );
}
